name: Deploy

on:
  push:
    branches: [ master ]
    paths:
      - 'lib/**'
      - 'test/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /${{ github.event.repository.name }}/
